# suppress inspection "UnusedProperty" for whole file

# Database

spring:
  application:
    name: bookstore-api_josinaldo
  datasource:
    schema: classpath:/db/migration/schema
    data: classpath:/db/migration/data
    url: jdbc:postgresql://localhost:5432/bookstore?createDatabaseIfNotExist=true&useSSL=true
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

# JPA properties
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  open-in-view: false
  generate-ddl: true
