# suppress inspection "UnusedProperty" for whole file

# Database
spring:
  profiles:
    active: dev
  application:
    name: bookstore-api_josinaldo
  datasource:
    schema: classpath:/db/migration/schema
    url: jdbc:postgresql://localhost:5432/bookstore?createDatabaseIfNotExist=true&useSSL=true
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  flyway:
    baseline-on-migrate: false
    enabled: false
    locations: classpath:/db/migration
# JPA properties
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
